# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Année')),
                ('date', models.DateField(verbose_name='état du')),
                ('scan', models.FileField(upload_to=finance.models.rename_bs_scan, verbose_name='Document')),
            ],
        ),
        migrations.AlterField(
            model_name='bankextract',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Année'),
        ),
    ]
