# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('type', models.IntegerField(choices=[(0, 'comité'), (1, 'commission'), (2, 'other')], default=0, verbose_name='Type')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='year',
            field=models.CharField(default=2017, max_length=25, verbose_name='Saison'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tél. mobile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tél. fixe'),
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='members.RoleType'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='role',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='role',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='role',
            name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('member', 'type')]),
        ),
    ]
