# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170810_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='title',
        ),
    ]
